server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/parkdb
    username: park
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update   # dev only; use migrations for prod
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.springframework.security: DEBUG
# Prefer ENV VARS for secrets in real environments, but this works for local dev
PAYOS_CLIENT_ID: 97300895-75a4-49fc-bb45-9d37291bdf96
PAYOS_API_KEY: aa2e5a31-c125-4f69-b86f-483f23223d62
PAYOS_CHECKSUM_KEY: 8012fa93a8d3681148c224c36ec91a8d39f2b9c90f3ef3cb5c95259b6ae447da

jwt:
  secret: change-me-very-long-random-string-at-least-32-bytes-11111111111111111111111
  expire-time: 86400
  issuer: change-me-issuer

gemini:
  api-key: AIzaSyDL4bvKRy3qkJz0HjihQg3PckjbU-3pb5U    # prefer env var in real use
  model: gemini-2.0-flash

app:
  internal-topup-confirm-url: http://localhost:8080/api/local/topups/confirm
  webhook:
    base-url: "https://scored-overall-humanity-oem.trycloudflare.com"  # update when tunnel changes
    path: /api/payment/payos/webhook
